### ISSUE TITLE
[FEATURE REQUEST] I would like to get the documentation of the package

### ISSUE THREAD

**Issue by flw-cn** [josa42/coc-go#103]
Just like this:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/5546718/92949723-261a1b80-f48e-11ea-917e-b1fcf7b1a715.png">

**Comment by josa42** [comment]
That's something that need to be done in `gopls`. Currently all that is provided is this:

![image](https://user-images.githubusercontent.com/423234/94601454-d3b16b00-0293-11eb-8b4e-de72930cac8f.png)
