### ISSUE TITLE
How to pass options for go.tags.add

### ISSUE THREAD

**Issue by Smithx10** [josa42/coc-go#106]
I'd like to have a hot key for omitempty and non omitempty.

autocmd FileType go nmap gty :CocCommand go.tags.add yaml<cr>  

How can I set options=yaml=omitempty in my mapping?

**Comment by josa42** [comment]
Add this to your `coc-settings.json`

```json
"go.tags": {
    "options": "yaml=omitempty"
  }
```

**Comment by Smithx10** [comment]
@josa42  

I was hoping to have 1 key binding for "yaml=omitempty" and 1 for just "yaml".  Sometimes in my code I'd like to omitempty for 1 line and not omit for another.    I believe editing the go.tags.options is global?

Sorry if I didn't explain that clearly.

**Comment by josa42** [comment]
@Smithx10 It can be global, or in your workspace. There is currently no way to pass it to `go.tags.add`

See [coc.nvim/wiki/Using-the-configuration-file](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#configuration-file-resolve)

**Comment by Smithx10** [comment]
@josa42  Would this be something added to gopls?

**Comment by josa42** [comment]
The the tags commands [fatih/gomodifytags](https://github.com/fatih/gomodifytags) is used. It would need to be added in `coc-go`:

https://github.com/josa42/coc-go/blob/5b41e9a51ca178c5211325f283498924b39f2b45/src/extension.ts#L174
https://github.com/josa42/coc-go/blob/5b41e9a51ca178c5211325f283498924b39f2b45/src/utils/modify-tags.ts#L21

I am not sure if want this to be added, to be honest though.

**Comment by josa42** [comment]
I have no plans to implement this. I might accept a PR
