### ISSUE TITLE
disable "loading snippets" 

### ISSUE THREAD

**Issue by zdmgmail** [josa42/coc-go#108]
if I use vim-rooter plugin, open a file will show "loading snippets" , is there any way to disable this ?

**Comment by zdmgmail** [comment]
now open every file while show this, even  current dir not change by vim-rooter

**Comment by josa42** [comment]
The "loading snippets" status item is part of [`coc-snippets`](https://github.com/neoclide/coc-snippets), not `coc-go`.

Seems like it can be disabled by [`snippets.enableStatusItem `](https://github.com/neoclide/coc-snippets/blob/master/package.json#L56)
