### ISSUE TITLE
When saving, the cursor jumps to a line that has a linting error

### ISSUE THREAD

**Issue by kminehart** [josa42/coc-go#109]
This is driving me crazy and i have no idea how to disable it. I'm fairly confident that it's coc-go.

How do I disable this functionality?

**Comment by josa42** [comment]
Not a coc-go functionality and I cannot reproduce the issue.

**Comment by kminehart** [comment]
Whoops, you're right. This is part of vim-go, under the `g:go_jump_to_error` option. Thank you!
