### ISSUE TITLE
Address of operator in completion of pointer

### ISSUE THREAD

**Issue by ldelossa** [josa42/coc-go#112]
When asking for a suggestion of a symbol prefixed by a asterisk (value dereference) completion suggests the symbol prefixed with the address of operator (&). The resulting suggestion is incorrectly "*&Symbol"

![image](https://user-images.githubusercontent.com/5642902/97038811-61057980-1539-11eb-8026-7d826722a646.png)

is this intended?

**Comment by josa42** [comment]
Completions are done by gopls, not by coc-go it self.
