### ISSUE TITLE
Diagnostics not showing in gutter or statusline

### ISSUE THREAD

**Issue by jim-at-jibba** [josa42/coc-go#113]
Hey,

Is there a way of showing errors in the gutter and in the status bar. This is how it works with the typescript server.
The errors show when I first open a file but they never get updated. I have to restart Coc to see the errors update. 

Like this:
<img width="837" alt="Screenshot 2020-10-24 at 14 58 28" src="https://user-images.githubusercontent.com/7897877/97083655-71852500-1609-11eb-9136-9e739a135651.png">

Hope that makes sense

**Comment by jim-at-jibba** [comment]
Seems to be working now. Strange

**Comment by jim-at-jibba** [comment]
So the icons show in the gutter but only when the file is first opened. This does not seem to update after first opening

**Comment by josa42** [comment]
I am pretty sure this is the same issue as #114
