### ISSUE TITLE
I'm getting `Organize import action not found` issue when saving

### ISSUE THREAD

**Issue by jponc** [josa42/coc-go#116]
![image](https://user-images.githubusercontent.com/4714727/97240379-3a4d8880-1842-11eb-987f-62ea0e10b323.png)

**Comment by jponc** [comment]
Here's my coc config json

```json
{
  "suggest.noselect": true,
  "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
  "go.goplsOptions": {
    "gofumpt": true
  },
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true
      }
    }
  }
}
```

**Comment by tracemeyers** [comment]
This happens to me as well but only when there's nothing new to import. There is no error when it can import a new package.
```
:CocCommand go.version
[coc.nvim] Version: coc-go 0.12.0; gopls 0.5.2
```

Here's the log from gopls when there is nothing new to import:
```
[Trace - 15:36:18.426 PM] Sending request 'textDocument/codeAction - (42)'.
Params: {"textDocument":{"uri":"file:///home/cat/go/src/t/main.go"},"range":{"start":{"line":0,"character":0},"end":{"line":145,"character":0}},"context":{"diagnostics":[],"only":["source.organizeImports"]}}


[Trace - 15:36:18.440 PM] Received response 'textDocument/codeAction - (42)' in 14ms.
Result: null
```
So probably a gopls issue but could be a coc issue too.

**Comment by josa42** [comment]
@jponc 
You seem to have `gopls` configured as `languageserver`, which does not use `coc-go`.

You can add `silent` to the autocmd to suppress the message:

```viml
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
```

**Comment by rogchap** [comment]
> You can add `silent` to the autocmd to suppress the message

@josa42 This has no affect to the `Organize import action not found` output when no new import are required.

**Comment by r03** [comment]
I have the same problem, but also when I use gopls without coc-go. I guess this is a gopls problem then?
(silent doesn't remove the message)

**Comment by weaming** [comment]
> @jponc You seem to have `gopls` configured as `languageserver`, which does not use `coc-go`.
> 
> You can add `silent` to the autocmd to suppress the message:
> 
> ```viml
> autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
> ```

this solved mine
