### ISSUE TITLE
Using CocAction('organizeImport') will cause my neovim stuck

### ISSUE THREAD

**Issue by JohnsonLee-debug** [josa42/coc-go#118]
Using autocmd BufWritePre *.go :call CocAction('organizeImport') will cause my neovim stuck. Coc asks me to choose an action but I can do nothing with it.
![2020-11-11_01-15](https://user-images.githubusercontent.com/53596783/98707776-61b46180-23bb-11eb-9441-6beab58e176e.png)

**Comment by NitroCao** [comment]
My neovim doesn't stuck. But coc.nvim complains `No source.organizeImports code action available`. I'm using goals `0.5.2`.

**Comment by JohnsonLee-debug** [comment]
> My neovim doesn't stuck. But coc.nvim complains `No source.organizeImports code action available`. I'm using goals `0.5.2`.

I replace it with autocmd BufWritePre *.go :call CocAction('runCommand', 'editor.action.organizeImport'), then the problem is solved. I'm using gopls 0.5.2.

**Comment by NitroCao** [comment]
> > My neovim doesn't stuck. But coc.nvim complains `No source.organizeImports code action available`. I'm using goals `0.5.2`.
> 
> I replace it with autocmd BufWritePre *.go :call CocAction('runCommand', 'editor.action.organizeImport'), then the problem is solved. I'm using gopls 0.5.2.

Now coc.nvim complains `Organize import action not found.` :(

**Comment by josa42** [comment]
You can suppress the message be adding `silent`:

```viml
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
```
