### ISSUE TITLE
How I can config tabsize of auto format code coc-go extension

### ISSUE THREAD

**Issue by vando2108** [josa42/coc-go#123]
![image](https://user-images.githubusercontent.com/35914996/101165256-5217e980-3604-11eb-805b-e517f147e4ca.png)
My default setting for tabsize is 2.
Thank you for your help <3

**Comment by rogchap** [comment]
> Gofmt's style is no one's favorite, yet gofmt is everyone's favorite. - Rob Pike

https://github.com/golang/go/issues/19618#issuecomment-287820267

**Comment by josa42** [comment]
I don't think that's possible.

You can set `tabstop` in vim of cause `¯\_(ツ)_/¯`
```viml
set tabstop=2
```
