### ISSUE TITLE
how to use the experimental codeLens

### ISSUE THREAD

**Issue by pjvds** [josa42/coc-go#124]
The readme lists an experimental codelens option. If I set that one to true, next to the coc codeLens.enable flag, nothing really happens.

Also `CocAction('codeLens')` can find any lenses for Go projects.

Is there anything I can do to use this experimental feature?

**Comment by josa42** [comment]
You need to enable code lenses in you `coc-settings.json`:

```json
{
  "codeLens.enable": true
}
```
=> [`doc/coc.txt` L575](https://github.com/neoclide/coc.nvim/blob/f805103eeb487b8d917b44977dca433f64c4fab6/doc/coc.txt#L575)

And map `<Plug>(coc-codelens-action)` to what ever yo like.

```viml
nmap <Leader>l <Plug>(coc-codelens-action)
```
=> [`doc/coc.txt` L1132](https://github.com/neoclide/coc.nvim/blob/f805103eeb487b8d917b44977dca433f64c4fab6/doc/coc.txt#L1132)

![image](https://user-images.githubusercontent.com/423234/103290206-43490a80-49e9-11eb-8c4b-b94b380a73aa.png)
