### ISSUE TITLE
vimspector integration

### ISSUE THREAD

**Issue by GopherJ** [josa42/coc-go#125]
recently coc-rust-analyzer added vimspector feature, it uses cargo to discover executable path. Is it possible to add this kind feature in coc-go?

**Comment by GopherJ** [comment]
example configuration of vimspector:

```json
{
    "configurations": {
        "codelldb - launch": {
            "adapter": "CodeLLDB",
            "configuration": {
                "type": "lldb",
                "request": "launch",
                "program": "${Executable}"
            }
        }
    }
}
```

example configuration of coc-rust-analyzer:
```json
    "rust-analyzer.debug.runtime": "vimspector",
    "rust-analyzer.debug.vimspector.configuration.name": "codelldb - launch",
```

**Comment by GopherJ** [comment]
![Peek 2020-12-11 00-08](https://user-images.githubusercontent.com/33961674/101840860-29807a00-3b45-11eb-973a-7eea448feb68.gif)

**Comment by josa42** [comment]
Is there any reason this needs to be part of `coc-go`? I would suggest to create a separate plugin for this.

**Comment by GopherJ** [comment]
I think it's good to be in one plugin so people can contribute together to that plugin, coc-rust-analyzer has already the support for this

**Comment by josa42** [comment]
I am closing this, b/c I have no plans implementing it and still feel it could be a separate extension.
