### ISSUE TITLE
[Feature Request] Allow using local go binaries

### ISSUE THREAD

**Issue by itaranto** [josa42/coc-go#130]
Hello, I'm not sure if there's a way to make coc-go use `gopls`, `gomodifytags`, etc by looking then in the `PATH`.
I want to avoid this plugin to download a bunch of binaries that I already have.

Thanks.

**Comment by josa42** [comment]
For `gopls`, you can set `go.goplsPath` to what ever binary you already have. I have no plans to anythong more in this direction.
