### ISSUE TITLE
CocRestart necessary after "go get"

### ISSUE THREAD

**Issue by ldelossa** [josa42/coc-go#137]
Hello,

If you have imported a package that does not exist in your package cache and "go get" it, coc.nvim will continue to report an error until CocRestart is called. 

Can this become dynamic?

**Comment by josa42** [comment]
I think this should be handled in gopls, not in coc-go.

**Comment by ldelossa** [comment]
Is that possible?

**Comment by ldelossa** [comment]
Something is off here, because using the native LSP features of Neovim, this never occurs.
