### ISSUE TITLE
Can't enable `go fmt` 

### ISSUE THREAD

**Issue by nehtreguy** [josa42/coc-go#138]
The command `autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')` from #135 is not working for me

**Comment by jeffg-hpe** [comment]
Try:
```
au FileType go au BufWritePre <buffer> <Plug>(coc-format)
```

**Comment by luisdavim** [comment]
this works for me:

```vim
" Organize imports on save
autocmd BufWritePre *.ts,*.js,*.py,*.rb,*.go :call CocAction('runCommand', 'editor.action.organizeImport')
```

**Comment by FotiadisM** [comment]
Facing the same problem.
Neither 
```vim
autocmd BufWritePre *.go :call CocAction('runCommand', 'editor.action.organizeImport')
```
nor
```vim
au FileType go au BufWritePre <buffer> <Plug>(coc-format)
```
works correctly. It only imports missing packages without formating the code.

**Comment by and3rson** [comment]
Can confirm that reorganizing imports works, but not the formatting.

Also, when saving the file again if the imports are already organized, an error is printed:

```
Error on request (runCommand): Vim(return):Error invoking 'runCommand' on channel 3 (coc):
"main.go" 93L, 2227C written
```

**Comment by and3rson** [comment]
Update: this one did the trick:

```vim
au BufWritePre *.go :call CocAction('format')
```

**Comment by luisdavim** [comment]
> @FotiadisM @kuka0len UPDATE - this one did the trick:
> 
> ```viml
> au BufWritePre *.go :call CocAction('format')
> ```

you don't really need that, you can set it up in your `coc-setings.json` with something like this:

```json
{
  "coc.preferences.formatOnSaveFiletypes": [
    "go",
    "graphql",
    "javascript",
    "javascriptreact",
    "json",
    "rust",
    "typescript",
    "typescript.tsx",
    "typescriptreact",
    "yaml"
  ]

}
```
