### ISSUE TITLE
Error loading workspace You are outside of a module and outside of $GOPATH/src

### ISSUE THREAD

**Issue by piotrromanowski** [josa42/coc-go#139]
Seeing the following error when loading up a Go project using bazel (https://bazel.build/). Is there a way to suppress/remove this error?

I've tried disabling workspace using
```
{
  "go.disable": {
    "workspaceFolder": true
  }
}
```
but that didn't work.

This is using the latest version of coc-go
coc-nvim "version": "0.0.80"
NVIM v0.5.0-dev+950-g5ce328df4
go version go1.14.1 linux/amd64

⠦ Error loading workspace You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module.
![image](https://user-images.githubusercontent.com/5794815/106620462-97429400-653f-11eb-94c1-b2b04229baa5.png)

**Comment by josa42** [comment]
I don't think that's possible.
