### ISSUE TITLE
The syntax check has a bug

### ISSUE THREAD

**Issue by lixiao189** [josa42/coc-go#140]
![](https://i.loli.net/2021/02/03/SA6OPQWBaEgqU9f.png)

See this picture, It says that I could not import the `fmt` package, However the package has been existed in my environment

This is the go env command's result

![](https://i.loli.net/2021/02/03/EnR4bWckQhmZ2zB.png)

**Comment by lixiao189** [comment]
Well, My system is the Mac OS big sur, and I install the go with the brew

**Comment by yaocccc** [comment]
I hava same bug with arch linux

**Comment by eeeXun** [comment]
I'm using manjaro linux,have the same problem, too.
And I use gopls, not use coc-go, produce this problem, too.

My coc-settings.json
```
{
    "languageserver": {
        "golang": {
            "command": "gopls",
            "filetypes": ["go"],
            "rootPatterns": ["go.mod"]
        }
    }
}
``` 
Might be the gopls problem?

**Comment by lixiao189** [comment]
Maybe
