### ISSUE TITLE
`~` does not expand in goplsPath

### ISSUE THREAD

**Issue by lordlabuckdas** [josa42/coc-go#143]
In `coc-settings.json` , I have `go.goplsPath` set to `~/go/bin/gopls` but on opening any go file, I get a message that says
```
goplsPath is configured ("~/go/bin/gopls") but does not exist
```
This issue is solved when I expand `~` with the absolute path manually.

It would be awesome if `~` is expanded like how it is done in  `coc-pyright`  for example.

Thank you!

Relevant code that might help:

* [coc-go/extension.ts#L50](https://github.com/josa42/coc-go/blob/fcb7ad0a61da8b6e04fa625aa2540f45e68c75bb/src/extension.ts#L50)
* [coc-pyright/configSettings.ts#L120](https://github.com/fannheyward/coc-pyright/blob/aecf18f197d10388c40dac9cfa4f0e4086591235/src/configSettings.ts#L120)

**Comment by luong-komorebi** [comment]
You have to use absolute path. This is the problem from upstream coc-nvim and the way they allow configurations to be declared, not a specific problem with coc-go

**Comment by lordlabuckdas** [comment]
@luong-komorebi, the `expand` function in [coc.nvim/src/workspace.ts#1042](https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L1042) takes care of path-related issues. `~` in the language server config (for `command`) in `coc-settings.json` works as expected.

**Comment by luong-komorebi** [comment]
Cool to know such capability. Let's wait for coc-go to enable it. My first comment was based on some of my experience digging the coc-nvim issue lists and my effort trying the same thing. Thus, it contained some outdated information as you pointed out
