### ISSUE TITLE
organizeImports CocAction doesn't format code

### ISSUE THREAD

**Issue by Palexer** [josa42/coc-go#145]
I don't know if this is a known issue or even an issue, but when I have the following command in my init.vim file and I save a not correctly formatted .go file, Coc only imports the missing modules, but does not format my code like the gofmt/goimports command line tools would do:
`autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')
`
I also tried
`au FileType go au BufWritePre <buffer> <Plug>(coc-format)`
but that gives me an error when executing "BufWritePre autocommand for "<buffer=1>"" when I save the file
Am I missing something or is it just not possible with coc-go to automatically format my Go code on save?

**Comment by jackieli-tes** [comment]
I believe if you have format on save on for go in `:CocConfig`:

```
  "coc.preferences.formatOnSaveFiletypes": [
    "go"
  ],
```

It automatically formats the code. or you can bind to a key to invoke it manually without saving:

```
nnoremap <leader>gi :call CocAction('runCommand', 'editor.action.organizeImport')<CR>
```

IMO, having it `BufWritePre` doesn't really make sense.

**Comment by Palexer** [comment]
Yeah, this is what I was looking for. Thanks!
