### ISSUE TITLE
Adding new snippet

### ISSUE THREAD

**Issue by sourabh-agrawal** [josa42/coc-go#146]
Hi i want to add a new snippet which adds a var block. We have block for constants, imports but var block is missing.
Is editing the snippet file is enough?

**Comment by sourabh-agrawal** [comment]
I have made changes in the snippet file, is this enough?
https://github.com/josa42/coc-go/pull/147

**Comment by josa42** [comment]
I am not maintaining any snippets, they are imported from the vscode extension.
