### ISSUE TITLE
Can't install binaries in Go1.16~

### ISSUE THREAD

**Issue by skanehira** [josa42/coc-go#148]
I'm try use coc-go in Go1.16 but I can't install binaries.

```
[coc.nvim] Error: Command failed: env GOBIN=/Users/skanehira/.config/coc/extensions/coc-go-data/bin go get golang.org/x/tools/gopls@latest
[coc.nvim] Failed to install 'gopls'
```

In my environment
```
MacbookPro13% go version
go version go1.16 darwin/arm64
```

It's seems like coc-go dosn't check go verison.
https://github.com/josa42/coc-go/blob/fcb7ad0a61da8b6e04fa625aa2540f45e68c75bb/src/utils/tools.ts#L30

**Comment by skanehira** [comment]
I resolved this problem.
The cause is `GO111MODULE` is set `auto` in my environment.
When I remove it and restart vim, the error is gone.

But, coc-go is setting`GO111MODULE: on`  when install binaries.
It's seems like env doesn't works.
https://github.com/josa42/coc-go/blob/4ee552edc0449f4d99741f53d7b385500e1da21e/src/utils/tools.ts#L84-L90

**Comment by josa42** [comment]
I have no plans to support go 1.16. You can manually install gopls and set `go.goplsPath`.
