### ISSUE TITLE
"Launching server "languageserver.go lang" using command gopls failed"

### ISSUE THREAD

**Issue by jamesmcl113** [josa42/coc-go#150]
`[coc.nvim] Server languageserver.golang failed to start: Launching server "languageserver.go
lang" using command gopls failed.`

I'm getting this error on opening a .go file. I've noticed that running `gopls` from the command line doesn't give any ouput, it just hangs indefinitely until I manually interrupt it. And running `:echo executable('gopls')` inside nvim returns 0, although I'm not really sure what this means.

My CocConfig (with stuff not related to the language server) looks like this:
`{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "trace.server": "verbose",
      "filetypes": ["go"]
    }
  }
}`

**Comment by josa42** [comment]
You have gopls configured as `languageserver`, which means it is unrelated to `coc-go`.
