### ISSUE TITLE
Go to definition and back

### ISSUE THREAD

**Issue by gh-liu** [josa42/coc-go#155]
After pressing a key which map to `<Plug>(coc-definition)` go to definition, I have to press `C-o` twice to go back.
First time it goes somewhere I do not know, sometime the first line of the file, second time it goes to the position where I want go back.

I use the config from the readme of coc.nvim and only install extension `coc-go`.

Is there any way to solve it?

**Comment by luisdavim** [comment]
i use this https://github.com/luisdavim/dotfiles/blob/master/files/vim/config/07.coc.vim#L32, and I can jump to definition with `C-]` and back with `C-t` it uses a stack.

**Comment by josa42** [comment]
This is not an coc-go issue, please report this at the coc.nvim repo.
