### ISSUE TITLE
gopls version mismatch

### ISSUE THREAD

**Issue by esn89** [josa42/coc-go#159]
I have `gopls` installed and it's 0.7.  The one on my command line says 0.70:
![iamge](https://imgur.com/CtWeUVY)

However, when I check it the coc-go version, it is a lower version of 0.40:

![image](https://imgur.com/gK4lizP)

I am trying to understand why this is the case.  Especially when I have checked and I have one gopls installed.

**Comment by luisdavim** [comment]
Try running `:CocCommand go.install.tools'` to update the tools.

**Comment by esn89** [comment]
That works, thank you.
