### ISSUE TITLE
Add support for `gojson`

### ISSUE THREAD

**Issue by luisdavim** [josa42/coc-go#161]
`gojson` allows converting `json` into a `go` `struct` it would be awesome to be able to paste some `json` into vim, select the text and have it converted into a `struct`

see:  https://github.com/ChimeraCoder/gojson

There's also a VSCode extension https://marketplace.visualstudio.com/items?itemName=maracko.json-to-go  from https://github.com/mholt/json-to-go

**Comment by josa42** [comment]
I won't add any more custom commands to this extension. May be you could create a separate extension.
