### ISSUE TITLE
Option to skip automatic installation of tools like 'gomodifytags' etc.

### ISSUE THREAD

**Issue by nikki93** [josa42/coc-go#164]
I'm not using these features currently. When using the plugin on Windows it complains with "Failed to install 'gomodifytags'" every time it starts. And I'm thinking to avoid looking into installing the tool since I don't use it. Would be nice to just ask coc-go to try to not auto install it start. Similar with 'gotests'.

**Comment by josa42** [comment]
coc-go does not install gomodifytags, unless you use a one of the `go.tags.*` commands or the `go.install.gomodifytags` command.

**Comment by nikki93** [comment]
I get the "Failed to install gomodifytags" error as soon as I open a Go file on Windows (ie., "every time it starts" as written in my original issue description). I don't have any references to `go.tags.*` in my vimrc or in coc-settings.json anywhere. It's possible this was fixed recently to only try to install when using a relevant command, will try after updating.
