### ISSUE TITLE
Auto completion replaces following word

### ISSUE THREAD

**Issue by tbo** [josa42/coc-go#167]
Whenever I auto complete something the following word is getting replaced. I wasn't able to find out if this behavior is coming from coc-go or gopls, but I assume it is related to the `insertReplaceSupport`. Other languages in my setup use my preferred behavior and don't modify anything after the insert (e.g. TypeScript doesn't). Is there any way to configure this?

**Comment by josa42** [comment]
Can't reproduce. It's probably unrelated to coc-go
