### ISSUE TITLE
Support `gopls.tidy`

### ISSUE THREAD

**Issue by luisdavim** [josa42/coc-go#168]
Usually when adding a new import to the file, `gopls` will report that the workspace is broken.
At this point we have to run  `go get` outside of vim and run `:CocRestart`
`gopls.tidy` would solve the problem as `gopls` would automatically refresh the workspace.

This was implemented on #154, but the PR was rejected.

**Comment by josa42** [comment]
`go.gopls.tidy` was added in #171. (I will probably rename it to `go.tidy`)
