### ISSUE TITLE
go 1.18 (currently in beta) breaks install

### ISSUE THREAD

**Issue by julianKatz** [josa42/coc-go#174]
My system golang is running a beta version of golang 1.18, and I'm seeing the following error when trying to open a golang file:

```
[coc.nvim] Error: Command failed: env GOBIN="/usr/local/google/home/juliankatz/.config/coc/extensions/coc-go-data/bin" go get golang.org/x/tools/gopls@latest
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

It looks like [your code](https://github.com/josa42/coc-go/blob/1096e07ae07978386c4d1b20806b942a358d04ee/src/utils/tools.ts#L47) should cover this problem, but perhaps I'm hitting an edge case in the regular expression.  My `go version` output is:

```
❯ go version
go version go1.18-pre10 ab/123456789 +12345678ab linux/amd64
```

I've changed some information to not include proprietary info.

**Comment by bietdoikiem** [comment]
Currently entering the same issue with coc-go. Hopefully they can get things done for us to trying out new Go Generics in NVim :(

**Comment by roberChen** [comment]
just simply modify the go install command in `tools.js` file.
```go
  30   │     (await goRun(`install ${source}@latest`)) && (await goBinExists(name));
```

note. I found that my local file is older than the repository version, though it's v1.1

**Comment by not-rusty** [comment]
It continues to break unfortunately. For anyone reading at this, deleting ` ~/.config/coc/extensions/coc-go-data/bin/gopls` and copying the latest gopls version (currently `0.8.1`) worked for me.

**Comment by tubzby** [comment]
Go 1.18 is released, this is a critical issue IMO.

**Comment by rbpatt2019** [comment]
Can't even do a clean install now, for the same reason. I'll see if I can figure out why, but for some reason the version catch is not correctly picking up that 1.18 is greater than 1.17, so we must use `go install` not `go get`...

**Comment by jackieli-tes** [comment]
obviously the workaround is quite straight forward:

1. install gopls using `go install golang.org/x/tools/gopls@latest`
2. `:CocConfig` and add option: 

```
  "go.goplsPath": "/home/jackieli/go/bin/gopls",
```

Change to your $HOME/go/bin or $GOBIN path

**Comment by jackieli-tes** [comment]
Ran into this one updating gofillstruct. The issue is at: https://github.com/josa42/coc-go/blob/master/src/utils/versions.ts#L7

Tests is saying `1.18` is not valid version: https://github.com/josa42/coc-go/blob/master/src/utils/versions.test.ts#L22

My fix: https://github.com/jackieli-tes/coc-go/commit/874b0e88841c322d520679aa549e18bfc6aaaacd

**Comment by more-pepsi** [comment]
I can fix the lsp features by setting the gopls path. However this errors seems to continue on after changing the gopls path

Why doe it try to istall to another place then GOPATH, I don't see an option to configure it to use the normal GOPATH?

```
[coc.nvim] Error: Command failed: env GOBIN="/Users/bill/.config/coc/extensions/c
oc-go-data/bin" go get github.com/cweill/gotests/...@latest
[coc.nvim] Failed to install 'gotests'
[coc.nvim] Error: Error: Command gotests not found! Run "CocCommand go.install.gotests"
to install it and try again.
```

**Comment by Frederick888** [comment]
@more-pepsi They're hard-coded at https://github.com/josa42/coc-go/blob/00fb0c096e3415f6494dcae5707c00759634f5a7/src/utils/tools.ts#L111-L120

But you can simply install them beforehand yourself, then `coc-go` won't try installing it again: https://github.com/josa42/coc-go/blob/00fb0c096e3415f6494dcae5707c00759634f5a7/src/utils/tools.ts#L23-L25

**Comment by luisdavim** [comment]
For the full set of tools:

```sh
env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install github.com/fatih/gomodifytags@latest
env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install github.com/cweill/gotests/...@latest
env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install github.com/haya14busa/goplay/cmd/goplay@latest
 env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install github.com/josharian/impl@latest
env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install golang.org/x/tools/gopls@latest
```
