### ISSUE TITLE
`json.Unmarshal` throws bad pointer error 

### ISSUE THREAD

**Issue by irateswami** [josa42/coc-go#176]
Currently, coc-go is complaining that pointer values are not being passed to `json.Unmarshal`. 

This seems to be the only functionality which throws this error currently. 

I am using 1.18rc1 as my current go. 

![image](https://user-images.githubusercontent.com/40923362/158451548-51a57099-e78d-4606-b443-8eb63875b1ea.png)

**Comment by luisdavim** [comment]
This relates to https://github.com/josa42/coc-go/issues/174

Try running:
```sh
env GOBIN="${HOME}/.config/coc/extensions/coc-go-data/bin" go install golang.org/x/tools/gopls@latest 
```

**Comment by irateswami** [comment]
Fixed with go tools reinstall.
