### ISSUE TITLE
`go.work` support

### ISSUE THREAD

**Issue by jackieli-tes** [josa42/coc-go#177]
At the time of writing, I haven't seen the syntax support for `go.work`. Opened: https://github.com/fatih/vim-go/issues/3373 hopefully it can be extracted just like https://github.com/mattn/vim-gomod

If above is done, we should send go.work files to lsp.

**Comment by josa42** [comment]
@jackieli-tes coc-go does not ship any syntax. Why not just install the package you linked?

**Comment by jackieli-tes** [comment]
@josa42  I wasn't talking about the syntax. It's the language id in here: https://github.com/jackieli-tes/coc-go/blob/master/src/extension.ts#L112

**Comment by luisdavim** [comment]
Can `gotexttmpl` and `gohtmltmpl` also be added?

**Comment by josa42** [comment]
Is gopls doing anything on those filetypes?

**Comment by jackieli-tes** [comment]
I believe yes:

In the [gopls features doc](https://github.com/golang/tools/blob/master/gopls/doc/features.md#template-files) it mentions text & html template completions within the `{{ }}` expressions

In code, it assigns languageId: https://github.com/golang/tools/blob/master/internal/lsp/source/util.go#L167

**Comment by josa42** [comment]
@jackieli-tes Thank you! I'll look into it.

**Comment by jackieli-tes** [comment]
btw, the `gotexttmpl` & `gohtmltmpl` filetypes is based the syntax detection I forked from vim-go. So if we want to keep it generic, i.e. only depend on syntax in standard neovim or vim distribution, some mapping is needed
