### ISSUE TITLE
Hide setting up workspace dialog

### ISSUE THREAD

**Issue by gaius-qi** [josa42/coc-go#183]
How to hide the setting up workspace dialog?

![image](https://user-images.githubusercontent.com/15955374/175953654-e10d7f6e-2008-45dd-9cb5-8e2279b02630.png)

**Comment by mrvon** [comment]
+1

**Comment by yaegassy** [comment]
@gaius-qi @mrvon Try it!

**coc-settings.json**:

```jsonc
{
  // ...snip
  "notification.disabledProgressSources": [
    "language-client-go"
  ],
  // ...snip
}
```

**Comment by mrvon** [comment]
@yaegassy It works! Thank you guy. By the way, We can't disable all progress notification by:
```
{
  // ...snip
  "notification.disabledProgressSources": [
    "*"
  ],
  // ...snip
}
```

**Comment by gaius-qi** [comment]
> @gaius-qi @mrvon Try it!
> 
> 
> 
> **coc-settings.json**:
> 
> 
> 
> ```jsonc
> 
> {
> 
>   // ...snip
> 
>   "notification.disabledProgressSources": [
> 
>     "language-client-go"
> 
>   ],
> 
>   // ...snip
> 
> }
> 
> ```

Thx
