### ISSUE TITLE
Coc Config for go.goplsOptions

### ISSUE THREAD

**Issue by sozoalvin** [josa42/coc-go#184]
hello! Was wonder if this is the right way to do it? 

Here is part of my config .. 
`go.goplsOptions`'s line throws the following error: 
_Property go.goplsOptions is not allowed_

Was wonder if im missing anything or that's not the right way to code it! 

```{
    "suggest.noselect": false,
    "diagnostic.warningSign": "!",
    "diagnostic.checkCurrentLine": true,
    "coc.preferences.formatOnSaveFiletypes": [
        "javascript",
        "javascriptreact",
        "html",
        "json",
        "css",
        "scss",
        "gohtml",
        "go",
        "yaml",
        "cpp"
    ],
    "go.goplsOptions": {
        "staticcheck": true,
        "experimentalWorkspaceModule": false
    },
```

**Comment by yaegassy** [comment]
I cannot reproduce this in my environment. Please update `coc.nvim` and `coc-go` to the latest version and try again
