### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by xiyaowong** [josa42/coc-go#185]
Automated scripts update settings, but are useless to users without publishing to npm.
Although it is possible to use this extension by building the source code, this is inconvenient

**Comment by rammiah** [comment]
gopls v0.9.0 is released, hints feature is not available in release v1.3.0, release a new version please

**Comment by yaegassy** [comment]
@rammiah Created PR for inlay hints support. https://github.com/josa42/coc-go/pull/187

**Comment by yaegassy** [comment]
Recent updates to coc.nvim allow inaly hints to be used without additional processing on the coc-extension side if the language server supports inlay hints.

- https://github.com/neoclide/coc.nvim/pull/3819

If coc.nvim is up to date, inlay hints are available.  My PR for coc-go is now closed.

**Comment by luisdavim** [comment]
Bump, it has been a while since the last release....

**Comment by luisdavim** [comment]
@josa42 is this project abandoned?

**Comment by josa42** [comment]
Settings updates are now automatically released
