### ISSUE TITLE
How can I stop the gopls update check

### ISSUE THREAD

**Issue by chenxuan520** [josa42/coc-go#186]
When I open Vim, it will automatically check gopls and download the updated installation of gopls, but this will make my Vim running very slow, so I don't want it to check and install it. I tried to set go.checkForupdates to "", but it didn't work. How should I set it so that it can stop checking for updates to gopls and let me maintain it in the current version

**Comment by yaegassy** [comment]
Set `disabled` and try it.

```jsonc
{
  // ...snip
  "go.checkForUpdates": "disabled",
  // ...snip
}
```

Or if `go.goplsPath` is set, the update feature itself will not work.

**Comment by chenxuan520** [comment]
thanks, everything is ok

**Comment by sjx95** [comment]
Sorry to comment on a closed issue. As I read file [commands.ts](
https://github.com/josa42/coc-go/blob/4047cd024394d571c06bd65c6e6bd24c8a6c2a24/src/commands.ts#L42) seems to define several available values for option `go.checkForUpdates`, such as 'disabled', 'install', 'ask', etc. Should we add this info to readme?

btw is there a way to disable binaries installing, and find it by $PATH? I tried to set goplsPath to `$(which gopls)` in `coc-config.json` but it doesn't work...
