### ISSUE TITLE
go.impl.cursor doesn't identify aliased packages.

### ISSUE THREAD

**Issue by preslavmihaylov** [josa42/coc-go#188]
Given this code:
```go
package main

import (
	alias "some/package/with/interface/v1"
)

func NewServer() *Server {
	return &Server{}
}

type Server struct{}

// < --- my cursor is here
```

If I execute `:CocCommand go.impl.cursor` and I input `s *Server v1.ServerInterface`, it works & correctly implements interface.
If I execute `:CocCommand go.impl.cursor` and I input `s *Server alias.ServerInterface`, it returns err `unrecognized interface: alias.ServerInterface`.

For reference, [vim-go](https://github.com/fatih/vim-go) handles this case correctly:
```
:GoImpl s *Server alias.ServerInterface
```

**Comment by josa42** [comment]
https://user-images.githubusercontent.com/423234/219872925-81d4dc04-5541-4c85-b8d1-6d5a928363c5.mov

But coc-go is just calling goimpl for this. Try running `CocCommand go.install.impl`, maybe the tool is out of date.
