### ISSUE TITLE
"go.goplsOptions": {"linkTarget": "false"} has unexpected behavior 

### ISSUE THREAD

**Issue by Chase-Lambert** [josa42/coc-go#190]
Expected behavior: The hover window should only display the function signature and doc string with nothing shown for doc links.

[gopls documentation detailing the expected behavior](https://go.googlesource.com/tools/+/refs/heads/master/gopls/doc/settings.md#linksinhover-bool)

Actual behavior: It still includes the link portion but instead of the actual link it just says "false" or "false" with an `http://false...` link.   

![Screenshot 2022-08-02 18 40 25](https://user-images.githubusercontent.com/51270719/182495089-46cf9b32-5fe6-42b9-a31f-db76d456a675.png)

Note: My screenshot shows the error twice due to what I assume is conflict error between gopls, vim-go plugin, coc.nvim, and/or coc-go. So maybe this whole unexpected error is with `gopls` itself since this would indicate `vim-go` and `coc-go` are getting the same unexpected result back and just presenting it a little differently. 

Thank you for your time!

**Comment by josa42** [comment]
That's working as expected.
> linkTarget controls where documentation links go. It might be one of:
>
>    "godoc.org"
>    "pkg.go.dev"


You want to set `linksInHover` to false.
