### ISSUE TITLE
Mangled text after selecting suggestion

### ISSUE THREAD

**Issue by luisdavim** [josa42/coc-go#191]
I'm not sure if the issue is with this extension or `coc.nvim` but it seems to be working fine with suggestions from other extensions.
In some cases, when selecting a suggestion from go's language server, it mangles the pre-existing text.

This is what's happening:
![out](https://user-images.githubusercontent.com/173006/185768264-eaed039a-9dcd-4935-927a-168818c2842b.gif)

**Comment by luisdavim** [comment]
I can work around the issue by setting `"suggest.snippetsSupport": false` so this might be an issue with `coc` itself and not necessarily this extension.

**Comment by rmzg** [comment]
I'm seeing something similar with text on the same line after I select a suggestion:

https://www.loom.com/share/f368f9f3aebb4a9c8c491c331328bc72

I have `uptime.Hours()` then type `math.Flo| uptime.Hours()` where | is the cursor and hitting tab results in `math.Floor() .Hours()`
[coc-errlog.txt](https://github.com/josa42/coc-go/files/9388550/coc-errlog.txt)

**Comment by rmzg** [comment]
[complete-coc-log.txt.gz](https://github.com/josa42/coc-go/files/9388555/complete-coc-log.txt.gz)

The complete log for more details

**Comment by rmzg** [comment]
Might be helped by `"suggest.fixInsertedWord": false,`

**Comment by rmzg** [comment]
If I use the `<down>` key to select `math.Abs` from the popup instead of `math.Floor` it doesn't delete `uptime` and I end up with `math.Abs()uptime...` as I would expect: 
[working-coc-log.txt.gz](https://github.com/josa42/coc-go/files/9388567/working-coc-log.txt.gz)

**Comment by luisdavim** [comment]
This is an issue with coc and not this extension.
