### ISSUE TITLE
Share editor state between separate nvim processes

### ISSUE THREAD

**Issue by korylprince** [josa42/coc-go#193]
For sake of example, I have two files:

**File a.go**
```go
package main
func main() {
    b()
}
```

**File b.go**
```go
package main
func b() {
}
```

If I have both files open in neovim via `:split`, and I rename `func b` to `func c`, the window with `a.go` would immediately show the unrecognized variable issue.

However, if I open each file separately in it's own instance of neovim, then the instance editing `a.go` would not see the change in `b.go` until I run `:CocRestart`.

I have verified that there's only one instance of `gopls serve ...`. There's one instance of `gopls -remote=auto` for each neovim instance, which I believe is correct.

Is it possible for the separate instances of neovim to "share state" so that changes in one file will be reflected in the other immediately like when using `:split`?

**Comment by josa42** [comment]
That's not something coc-go can or should do.
