### ISSUE TITLE
Odd formatting for math operations

### ISSUE THREAD

**Issue by npearson72** [josa42/coc-go#197]
For some reason the spacing around arithmetic operators is different. For `*` and `/` there is no surrounding white space. For `+` and `-` there is.

Is this expected behavior? I'd prefer they be consistent. Possible with a config?

<img width="346" alt="Screen Shot 2022-11-29 at 12 20 55 PM" src="https://user-images.githubusercontent.com/1323414/204627072-8bd7f561-3e60-4f80-b021-e33703f2fecd.png">

**Comment by josa42** [comment]
[gopls](https://github.com/golang/go/labels/gopls) does the formatting, not coc-go
