### ISSUE TITLE
Code lens not working on unit test functions.

### ISSUE THREAD

**Issue by tubzby** [josa42/coc-go#202]
I have setup vimspector, nothing happens after CocActionAsync('codeLensAction'), but go.mod file is working:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/16208625/217120925-6afabe20-2012-4821-b20b-8d4f577eae22.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/16208625/217120984-9ed7be7f-0dd8-4eb7-bb7c-af9d7596c77f.png">

**Comment by tubzby** [comment]
I have enabled it by adding to CocConfig with:

```
	"go.goplsOptions": {
		"codelenses": {
			"test": true,
		},
		"semanticTokens": true,
		"staticcheck": true
	}
```

Now "run test" is working, but "debug test" is not working, I have set up delve and vimspector, what might be missing?
![image](https://user-images.githubusercontent.com/16208625/217233101-1d0624cb-995f-4e82-b760-1cb3c7cd68da.png)

**Comment by josa42** [comment]
That's nothing, that can be fixed in coc-go. Must be something with your configuration
