### ISSUE TITLE
How to not load snippets in go.json

### ISSUE THREAD

**Issue by pacmanzou** [josa42/coc-go#208]
Hi, I tried every option of go.disable in coc-settings.json, but there is no way to solve it. Can you tell me how to do? I just want to use my go.snippets.

**Comment by josa42** [comment]
You should be able to use the `snippets.excludePatterns` option:
=> https://github.com/neoclide/coc-snippets#options

Something like:
```json
{
    "snippets.excludePatterns": ["**/coc-go/snippets/go.json"]
}
```
