### ISSUE TITLE
Import warnings don't disappear after `go mod tidy`.

### ISSUE THREAD

**Issue by your-diary** [josa42/coc-go#209]
When I import some external package, an import warning is displayed as expected:

![Screenshot 2023-07-12 at 15 52 51](https://github.com/josa42/coc-go/assets/58146437/b7a6512c-378e-49b4-8735-79b86e469c81)

However, even after I execute `:! go mod tidy` inside Vim, the warning is still there (though `:! go build` succeeds now). Reopening the buffer via `:e` command doesn't remove the warning either.

My only workarounds are to restart the server (i.e. `:CocRestart`) or to close Vim entirely and restart it (i.e. `:q` and `$ vim main.go`).

Is this behavior expected?

**Comment by andryuha-salo** [comment]
have you tried auto fix import on save?

**Comment by your-diary** [comment]
I'm VERY sorry I just noticed I don't use `coc-go` while reviewing `:CocConfig`. I was just using [`gopls` with `coc.nvim`](https://github.com/neoclide/coc.nvim/wiki/Language-servers#go).

**Comment by violin0622** [comment]
I meets the same issue, and I'm sure I was using `coc-go`.  
I can run `CocCommand go.gopls.tidy` to download module and modify go.mod file, but after that, the warning still there.
