### ISSUE TITLE
SemanticToken base highlighting ? 

### ISSUE THREAD

**Issue by violin0622** [josa42/coc-go#212]
Is coc-go support semantic token highlighting ? 
`gopls` has implemented it and VS-code has supported it. But I searched through readme and issues list, can't found any document about how to configure it with coc-go . 

I've tried config like this but helpless:

```json
{
  ,"go.goplsOptions": {
    ,"semanticTokens": true
  }
}

```

**Comment by Hogan-TR** [comment]
I'm the same way, or is there any workaround?

**Comment by andryuha-salo** [comment]
`:h coc-semantic-highlights`
enable on coc.nvim side, on gopls side and it should work 

`:CocCommand semanticTokens.inspect`
![image](https://github.com/josa42/coc-go/assets/122885979/0756b902-c9fd-46f0-8795-a50ba4bc9d8d)

also your theme should support these hl groups

**Comment by violin0622** [comment]
> `:h coc-semantic-highlights` enable on coc.nvim side, on gopls side and it should work
> 
> `:CocCommand semanticTokens.inspect` ![image](https://user-images.githubusercontent.com/122885979/264002582-0756b902-c9fd-46f0-8795-a50ba4bc9d8d.png)
> 
> also your theme should support these hl groups

It works. Thank you !
