### ISSUE TITLE
How to set the options like "usePlaceholders"?

### ISSUE THREAD

**Issue by noalias** [josa42/coc-go#49]
How can I set the options described in [here](https://github.com/golang/tools/blob/master/gopls/doc/settings.md)?

When I set them in `coc-settings.josn` like 
![IMG_20191018_142553](https://user-images.githubusercontent.com/42366661/67071376-f5196400-f1b4-11e9-98f9-b5c6bf9afb07.jpg)
whith `coc-go` enabled, the completion items display twice!

**Comment by mnrce** [comment]
@noalias: Hi, I have same question, have you been able to solve this?
If yes, can you share your solution?
If no, please re-open this issue so that the author can look into it.

**Comment by noalias** [comment]
@mnrce set `go.enable: fasle` in  `coc-settings.jion`

**Comment by mnrce** [comment]
> @mnrce set `go.enable: fasle` in `coc-settings.jion`

I don't think that's the solution, since setting that config to `false` will disable `coc-go`.
The point of coc-extension is to provide non-lsp-standard feature of the lsp server, i.e [custom commands](https://github.com/josa42/coc-go#commands).

**Comment by josa42** [comment]
@noalias Then you set the `languageserver` in `coc-setting.json` the way you did you actually do not need `coc-go`. Technically set `go.enable` to `false` globally, it will disable `coc-go` all together, so may as well uninstall it.

**Comment by josa42** [comment]
I will add a `go.goplsOptions` configuration block in the next release of `coc-go`, which will enable you to set initalization options for gopls.

**Comment by noalias** [comment]
@josa42 Thank you!
