### ISSUE TITLE
Add information on interaction with vim-go

### ISSUE THREAD

**Issue by condekind** [josa42/coc-go#52]
[vim-go](https://github.com/fatih/vim-go) is an extremely popular vim/nvim plugin. Maybe it would be nice to elaborate on the interaction between vim-go and coc-go?

I use vim-go and coc, it would be nice to have this info on Readme.md

**Comment by josa42** [comment]
There really is not interaction between `coc-go` and `vim-go`.

With `coc-go` I do not aim to recreate the features of `vim-go`. For now, the main goal is to provide a convenient way to install `gopls` and use it with `coc.nvim`.

If you need more than the features provided by `gopls`, you are probably better of with [`vim-go`](https://github.com/fatih/vim-go) or [`govim`](https://github.com/govim/govim).
