### ISSUE TITLE
Delay before initializing compared to "languageserver" definition

### ISSUE THREAD

**Issue by dezza** [josa42/coc-go#53]
I've noticed compared to running the usual coc.nvim gopls configuration:

```
"languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true
      }
    }
  }
```
 This takes quite a long time 10-20s to initialize and populate the completion popup, it will only show the universal completions `[B] [buffer] [A] [around] [F] [file]` by keywords (NOTE: I use the `"suggest.autoTrigger": "none"` with the tab mappings btw.

**Additional question regarding this plugin**
I'd also appreciate if you could clarify this extension. I'm new to both coc.nvim, languageservers, I've transitioned to coc.nvim just recently.

1. As I understand it and from reading all the issues here, it is a wrapper/extension around the gopls language server - and hence the "languageserver" option isn't necessary anymore (Please confirm?)

2. Should more or less work out of the box after `:CocInstall coc-go` without further configuration needed.

3. Would you recommend something else alongside it? I'm mainly interested in completion, imports, snippets for my languages and this seems to simplify the whole stack quite a bit which is just awesome 🎉 🌟 

Thanks for your effort btw, I greatly appreciate it, add it here when you feel like it 👍 https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#implemented-coc-extensions

**Comment by josa42** [comment]
> This takes quite a long time 10-20s to initialize and populate the completion popup, it will only show the universal completions [B] [buffer] [A] [around] [F] [file] by keywords (NOTE: I use the "suggest.autoTrigger": "none" with the tab mappings btw.

That's not supposed be happening :-D But from the supplied information I cannot reproduce it.

> 1. As I understand it and from reading all the issues here, it is a wrapper/extension around the gopls language server - and hence the "languageserver" option isn't necessary anymore (Please confirm?)
> 
> 2. Should more or less work out of the box after :CocInstall coc-go without further configuration needed.

That's the goal at least. Additionally I added, couple commands [commands](https://github.com/josa42/coc-go#commands), using other go [tools](https://github.com/josa42/coc-go#tools). 

If you prefer to control the version of `gopls`, you are probably better off configuring it as a `languageserver` without this extension.

> Would you recommend something else alongside it? I'm mainly interested in completion, imports, snippets for my languages and this seems to simplify the whole stack quite a bit which is just awesome 🎉 🌟

Completion and imports should be handled by this extension, for snippets you can use [`coc-snippets`](https://github.com/neoclide/coc-snippets).

> Thanks for your effort btw, I greatly appreciate it, add it here when you feel like it 👍 https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#implemented-coc-extensions

I will, as soon as this reaches 1.0.0

**Comment by dezza** [comment]
Seems like I had a problem somewhere, I forgot what I changed as I played with it for quite some time. In the end it does take a few secs before it reacts on compiler errors and can complete for me, even with a more or less clean and minimal coc.nvim "setup" vimrc.

Thanks for the effort!

**Comment by dezza** [comment]
Delay was due to: https://github.com/neoclide/coc.nvim/issues/1447
