### ISSUE TITLE
coc-go and gopls

### ISSUE THREAD

**Issue by luisfelipemourapereira** [josa42/coc-go#54]
I am attempting to use gopls with coc-go.  I do have followed all documentation so far.

in testing with some files I see this in CocInfo

 54 [Info  - 12:22:07 PM] 2019/12/31 12:22:07 using the -modfile flag is disabled
 55         directory = /Users/luis/code/github/luis/terraform-provider-google
 56 [Info  - 12:22:08 PM] 2019/12/31 12:22:08 go/packages.Load
 57         query = ./...
 58         packages = 6
 59 2019/12/31 12:22:10 no diagnostics: context canceled
 60         URI = file:///Users/luis/code/github/luis/terraform-provider-google/version/version.go
 61 2019/12/31 12:22:10 no diagnostics: context canceled
 62         URI = file:///Users/luis/code/github/luis/terraform-provider-google/google/access_context_manager_operation.go
 63 2019/12/31 12:22:10 no diagnostics: context canceled
 64         URI = file:///Users/luis/Library/Caches/go-build/b6/b66be15d9a09b2f7b4a4cf5d9c5ccc7151abd3a7b1939d39e0d04cecec0d86fd-d
 65 2019/12/31 12:22:10 no diagnostics: context canceled
 66         URI = file:///Users/luis/code/github/luis/terraform-provider-google/google/access_context_manager_operation.go
 67 [Error  - 12:22:10 PM] 2019/12/31 12:22:10 no diagnostics: context canceled
 68         URI = file:///Users/luis/code/github/luis/terraform-provider-google/version/version.go
 69 [Error  - 12:22:10 PM] 2019/12/31 12:22:10 no diagnostics: context canceled
 70         URI = file:///Users/luis/Library/Caches/go-build/b6/b66be15d9a09b2f7b4a4cf5d9c5ccc7151abd3a7b1939d39e0d04cecec0d86fd-d
 71 [Error  - 12:22:10 PM] 2019/12/31 12:22:10 no diagnostics: context canceled
 72         URI = file:///Users/luis/code/github/luis/terraform-provider-google/google/access_context_manager_operation.go
 73 [Error  - 12:22:10 PM] 2019/12/31 12:22:10 no diagnostics: context canceled
 74         URI = file:///Users/luis/code/github/luis/terraform-provider-google/google/access_context_manager_operation.go
 75 2019/12/31 12:22:12 : context canceled
 76 [Error  - 12:22:12 PM] 2019/12/31 12:22:12 : context canceled

When I am in my file I cannot seem to trigger any gopls based completions.

I have installed with CocInstall coc-go

there are no errors In terms of extension installation.  I'd love to get this documented so someone else doesn't run into this.  Is there anything I could provide that would help?

**Comment by josa42** [comment]
Should be fixed in `0.6.1` (thanks to @benwainwright: #55)
