### ISSUE TITLE
[Feature Request] gopls type info support

### ISSUE THREAD

**Issue by douglarek** [josa42/coc-go#59]
@josa42 Thanks for this great coc plugin ! would you like to add gopls type info command like `vim-go`'s `:GoInfo`, thanks again.

**Comment by josa42** [comment]
@douglarek 
Is `:call CocAction('doHover')` what you are looking for?

![image](https://user-images.githubusercontent.com/423234/73664158-3a4b9e00-469f-11ea-9fbe-cdd6c9ce3643.png)

But, this is not the scope if this plugin. Which mainly provides a convenient way to install [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md) for [`coc.nvim`](https://github.com/neoclide/coc.nvim). So I am going to close this issue.
