### ISSUE TITLE
does not install gopls on windows

### ISSUE THREAD

**Issue by cybercatgurrl** [josa42/coc-go#6]
I get `'GOPATH' is not recognized as an internal or external command` after installing the extension.

**Comment by rickywu** [comment]
The same on Windows

```
C:\Users\Ricky>where gopls
D:\DevTools\gopath\bin\gopls.exe

C:\Users\Ricky>echo %GOPATH%
D:\GoTools\gopath
```

But coc.nvim got error:
`
[coc.nvim] Server gopls failed to start: Command "C:\Users\Ricky\.config\coc\go\bin\gopls" of go is not executable: Error: not found: C:\Users\Ricky\.config\coc\go\bin\gopls
`
Where should I config use GOPATH to find gopls?

**Comment by oz** [comment]
This may be related.

The same error now happens on Linux. The fish shell does not support the `GOPATH=blabla` prefix to run a command with a given environment variable.

```
fish: Unsupported use of '='. To run 'go' with a modified environment, please use 'env GOPATH=/home/oz/.config/coc/extensions/coc-go-data/tools go…'                                                            
  GOPATH=/home/oz/.config/coc/extensions/coc-go-data/tools go get -d -u github.com/fatih/gomodifytags
```

This worked fine previously. I guess the `0.2` release introduced the bug.

**Comment by oz** [comment]
A fix for my previous issue on Linux (using the fish shell): `set shell=/bin/sh` in your vim/neovim config. file, and _voilà_.

Also, if you already have a `GOPATH` populated with code or cache pkg files, I found that this helps a lot to avoid re-downloading everything...

```shell
rm -fr ~/.config/coc/extensions/coc-go-data
ln -s $GOPATH coc-go-data
```

:innocent:

**Comment by mattn** [comment]
I got same on Windows. And I figure out this. But below fix this issue.

```
cd %LOCALAPPDATA%\coc\coc-go-data\bin
copy gopls.exe gopls
```
Probably, which function does not treat `.exe`.

**Comment by qige96** [comment]
@mattn Thanks! Your solution fix this bug on my computer! One difference is that the `coc-go-data` path on my computer is `%LOCALAPPDATA%\coc\extensions\coc-go-data\bin`, and I just need to copy my `gopls.exe` to this directory, without renaming it to `gopls`

**Comment by wsw0108** [comment]
https://github.com/josa42/coc-go/blob/38b0b30355f85a7952a2e6602fdb1cdf9141a501/src/utils/tools.ts#L69-L75

```
import { workspace, runCommand } from 'coc.nvim'

  const env = { GOBIN: gobin, GOPATH: gopath, GO111MODULE: 'on' }
  const cmd = `go ${args}`
  const opts = {
    env: Object.assign({}, process.env, env),
    cwd: gopath
  }

  try {
    await runCommand(cmd, opts)
  } catch (ex) {
    workspace.showMessage(ex)
    return false
  }
```

Below should fix this issue.

**Comment by warrenb95** [comment]
> 
> 
> I got same on Windows. And I figure out this. But below fix this issue.
> 
> ```
> cd %LOCALAPPDATA%\coc\coc-go-data\bin
> copy gopls.exe gopls
> ```
> 
> Probably, which function does not treat `.exe`.

This fixed it for me on windows! Absolute legend, thanks!
