### ISSUE TITLE
Is there a way to use this and golangci-lint?

### ISSUE THREAD

**Issue by uri** [josa42/coc-go#61]

**Comment by josa42** [comment]
`coc-go` has not integration with linter, and I currently have no intention of changing that.

**Comment by EvanPurkhiser** [comment]
I'm curious why you don't intend to ever support `golint`?

**Comment by josa42** [comment]
> I'm curious why you don't intend to ever support `golint`?

Currently, I want to focus on `gopls` and don't bloat the extension.
If you need `golint` support, you could write e separate coc extions like: `coc-golint`.
