### ISSUE TITLE
Autocompletion and help "windows" overlap…

### ISSUE THREAD

**Issue by kierun** [josa42/coc-go#66]
I install `vim-go` as well as `coc-go` and I am getting this weird behaviour:

![screenshot](https://user-images.githubusercontent.com/3079575/76396560-54009500-6371-11ea-986e-fdce72d68b7f.png)

The "windows" overlap which make it rather difficult to see what is going on.

*What am I doing wrong?*

**Comment by kierun** [comment]
I got ride of `vim-go` and actually enabled the language client side of things and now I am using just `coc-go`. Sadly, I am still getting the above…

**Comment by josa42** [comment]
I don't think this is related t `coc-go`, as all the UI is handled by `coc.nvim`.
