### ISSUE TITLE
renaming functionality

### ISSUE THREAD

**Issue by esn89** [josa42/coc-go#70]
Hi there, is there a way to do refactoring, namely to use coc's rename?

**Comment by kovetskiy** [comment]
I am also interested in this feature

**Comment by josa42** [comment]
You need to add a key map. This is the example mapping from [`coc.nvim`](https://github.com/neoclide/coc.nvim#example-vim-configuration)

```go
nmap <leader>rn <Plug>(coc-rename)
```

![nvim](https://user-images.githubusercontent.com/423234/82298512-856e9000-99b4-11ea-8b1f-7216c2ef715f.gif)
