### ISSUE TITLE
Possible to run golint on save?

### ISSUE THREAD

**Issue by esn89** [josa42/coc-go#72]
Hi, 

I was wondering if it's possible to run golint on saving the file.

**Comment by raahii** [comment]
I think it is impossible using this plugin only. I know two solutions to use golint with coc.nvim.

1. lint using [ALE](https://github.com/dense-analysis/ale)

    Coc.nvim has `displayByAle` option. By setting this option to true and setting golint in ALE, you can see its diagnosis. But ALE is not supporting floatwindow, I don't like the look of it very much. ([issue](https://github.com/dense-analysis/ale/issues/2418))
```
"diagnostic.displayByAle":~
	Use ALE for displaying diagnostics. This will disable coc.nvim for
	displaying diagnostics. Restart to make changes take the effect, default:
	`false`
```

2. lint using [iamcco/coc-diagnostic](https://github.com/iamcco/coc-diagnostic)

    coc-diagnostic is coc extention of [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver). It is general purpose Language Server that integrate with linter to support diagnostic features.
   After installing coc-diagnostic, you can set up golint in `coc-setting.json` like this:

```
{
  ...

  "languageserver": {
    "dls": {
      "command": "diagnostic-languageserver",
      "args": ["--stdio"],
      "filetypes": [ "go" ],
      "initializationOptions": {
        "linters": {
          "golint": {
            "command": "golint",
            "rootPatterns": [],
            "isStdout": true,
            "isStderr": false,
            "debounce": 100,
            "args": [],
            "offsetLine": 0,
            "offsetColumn": 0,
            "sourceName": "golint",

            "formatLines": 1,
            "formatPattern": [
              "^[^:]+:(\\d+):(\\d+):\\s(.*)$",
              {
                "line": 1,
                "column": 2,
                "message": [3]
              }
            ]
          }
        },
        "formatters": {},
        "filetypes": {
          "go": "golint"
        },
        "formatFiletypes": {}
      }
    }
  }
```

**Comment by josa42** [comment]
No, this extension does not integrate with `golint`.

**Comment by ZenLian** [comment]
If you just want formatting on saving, It's configurable in coc-settings.json:
``` json
"coc.preferences.formatOnSaveFiletypes": ["go"]
```

**Comment by esn89** [comment]
Perfect, that's what I'm looking for.  Thank you ZenLian.

**Comment by esn89** [comment]
@ZenLian do you know which tool does the formatting?

**Comment by ZenLian** [comment]
> @ZenLian do you know which tool does the formatting?

This is done by specific language server. Here `gopls` does the job for golang.
