### ISSUE TITLE
coc-go and vim-go sharing a gopls server woes.

### ISSUE THREAD

**Issue by ygworldr** [josa42/coc-go#76]
I have been following [this guide](https://github.com/fatih/vim-go/issues/2760#issuecomment-596074572) to get the gopls shared between `coc-go` and `vim-go`. [Another user, in a different issue](https://github.com/fatih/vim-go/issues/2807#issuecomment-609503792) could not get it to work.

However, I think it should be possible! Here is my configuration. 

In `~/.config/nvim/init.vim`:

```
let g:go_gopls_enabled = 1
let g:go_gopls_options = ['-remote=auto']
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_referrers_mode = 'gopls'
```
and `.vim/coc-settings.json`:

```
{
    "diagnostic.errorSign": "✖",
    "diagnostic.warningSign": "⚠",
    "diagnostic.infoSign": "ℹ",
    "diagnostic.hintSign": "➤",
    "diagnostic.checkCurrentLine": true,
    "suggest.floatEnable": false,
    "languageserver": {
        "golang": {
            "command": "gopls",
            "args": ["-remote=auto"],
            "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
            "filetypes": ["go"]
        }
    },
    "go.goplsOptions": {
        "go.goplsOptions": ["-remote=auto"]
  }
}
```

_What am I not understanding and therefore doing wrong?_

**Comment by ygworldr** [comment]
The main problem is that I have dozens of `gopls` running which are eating all the CPU and RAM on my machine. Sharing would help alleviate that problem.

**Comment by ygworldr** [comment]
`coc-go` uses `gopls` 0.3… which is known for having some memory leak. Maybe updating that would help?

**Comment by josa42** [comment]
> `coc-go` uses `gopls` 0.3… which is known for having some memory leak. Maybe updating that would help?

`coc-go` has no specific `gopls` version bundled. Run `:CocCommand go.install.gopls` to update gopls.

**Comment by josa42** [comment]
@ygworldr It looks to me that you are running `gopls` without `coc-go` or possibly even twice. If you have `coc-go` installed you do not need the `languageserver` configuration.

So you need to either uninstall `coc-go` or remove the `gopls`
 configuration from `languageserver` in your `coc-settings.json`.

**Comment by wavded** [comment]
FWIW, I disable gopls for vim-go with `let g:go_gopls_enabled = 0` and also do not use it for ale, just for `coc.nvim` stuffs.

**Comment by mazhigali** [comment]
@ygworldr in your .vim/coc-settings.json   fill "command": "/home/FULL_PATH/gopls". It helped me

**Comment by winzenith** [comment]
> FWIW, I disable gopls for vim-go with `let g:go_gopls_enabled = 0` and also do not use it for ale, just for `coc.nvim` stuffs.

I did put this line but it doesn't seem to work, this way was still end up like open two instances of gopls at same time, and the memory usage were both up to 200MB~  . But after working with the issue, I am not sure if I got this right, i eventually had two instance but one of them seems to remote the main instance of gopls which has memory usage around 199MB yet, and another instance only has 20MB~. 
What I did is to put this line ```"go.goplsArgs": ["-remote=auto"]``` in ```coc-settings.json``` and leave ```let g:go_gopls_enabled = 0``` this setting with vim-go as well. And it works like I've described as above. Please let me know if there is any better way to address this issue about duplicate instance of gopls.

**Comment by rydesun** [comment]
The gopls arg `--remote=auto` means to setup a gopls server, and some clients connect to it. The server consumes a lot of memories, but clients do not.

If you set coc-go and vim-go both `--remote=auto`, these plugins will launch their server separately, and their clients also connect to their server separately.

So there will be two servers.

If you only want one server, according to this [gopls doc](https://github.com/golang/tools/blob/master/gopls/doc/daemon.md#managing-the-daemon-manually), you can manually start gopls server yourself, the server listen at tcp or unix socket.  Then let gopls clients from vim-go and coc-go connect to same server.

So there will be only one server instance, and some client instances.

In Linux OS, first launch gopls server:
```shell
gopls -listen="unix;/tmp/gopls-daemon-socket"
```
The gopls server will create a unix domain socket file at `/tmp` directory.

The coc-go and vim-go setting:

In `coc-settings.json`:
```
"go.goplsArgs": ["-remote", "unix;/tmp/gopls-daemon-socket"],
```
And in `init.vim`:
```shell
let g:go_gopls_options = ['-remote=unix;/tmp/gopls-daemon-socket']
```

You can read the gopls doc I metioned for more information.

If you want to restart gopls, you should remove `/tmp/gopls-daemon-socket` first, overwise it will fail.

To make life easier, This time I use systemd to manage my gopls server.

In `.config/systemd/user/gopls.service`
```systemd
[Unit]
Description=Go language server.

[Service]
Restart=on-failure
ExecStart=/usr/bin/gopls -listen="unix;/tmp/gopls-daemon-socket"
ExecStartPre=/usr/bin/rm -f /tmp/gopls-daemon-socket

[Install]
WantedBy=default.target
```
I can start gopls server by running this command:
```shell
systemctl restart --user gopls.service
```

**Comment by ygworldr** [comment]
> The gopls arg --remote=auto means to setup a gopls server, and some clients connect to it. The server consumes a lot of memory, but clients do not.

No kidding. I get regularly 4/5 G of RAM just to run the server.

**Comment by rydesun** [comment]
@ericwq 

> could you provide a sample of coc-setting.json with go.goplsArgs?

`go.goplsArgs` is a setting provided by coc-go, and coc will only recognize it after coc-go is installed.

You decided to uninstall coc-go, and configure `languageserver.golang` in coc-setting.json.
So the way you make gopls work is to have coc communicate directly with gopls:

```text
coc => gopls
```

And the way I'm talking about is to let coc-go determine which gopls to use.
They work in the following way:

```text
coc => coc-go => gopls
```
coc-go wraps gopls so that coc can use it.

In doing so, you don't need to configure `languageserver.golang`. Instead, use `go.goplsArgs`
and `go.goplsPath` to configure.

Both ways are valid.

**Comment by ericwq** [comment]
@rydesun using the following way as you suggested.
```
coc => coc-go => gopls
```

**Comment by ericwq** [comment]
see [this](https://github.com/ericwq/golangIDE/blob/master/shared-gopls-daemon.md) for the reason.

**Comment by KianYang-Lee** [comment]
Useful stuff, feel like this deserves its own mention on the README. I also made the same mistake by defining both `languageserver` and `go.gopls`, which causes really awkward behaviour
