### ISSUE TITLE
You are neither in a module nor in your GOPATH error

### ISSUE THREAD

**Issue by idopshik** [josa42/coc-go#77]
I've already opened that issue on golang section:
https://github.com/golang/go/issues/38720
in two words - it's not a gopls's fauls.

I reinstalled everything anew, use clean and small vimrc and got this error anyway.
Is there a way to disable this error (even using some harsh methods like disabling all errors from LS)?

**Comment by josa42** [comment]
Please, add more information on how to reproduce the issue.

**Comment by mhersson** [comment]
I noticed the same problem when my project was not containing a `.git` folder. Adding `go.mod` to the rootPatterns in coc-settings.json solved it for me

```{
  "go.goplsOptions": {"completeUnimported": true},
  "coc.preferences.rootPatterns": [
      ".git",
      ".hg",
      ".projections.json",
      "go.mod"
  ]
}

**Comment by idopshik** [comment]
Thanks. Very appreciate your help.
