### ISSUE TITLE
error installing `gotest` & `gopls` on Go versions < 1.13

### ISSUE THREAD

**Issue by nathanshelly** [josa42/coc-go#79]
First off, thanks for making this extension!

I'm running into an issue installing `gotest` & `gopls` for Go v1.12. After installing the extension via `:CocInstall coc-go` and opening a Go file I see `Installing gotests...`, `Installing gopls...` loaders and then the following error:

```
[coc.nvim] Error: exited with 1
Error: Command failed: env GOBIN=/Users/nathan/.config/coc/extensions/coc-go-data/bin GOPATH=/Users/nathan/.config/coc/extensions/coc-go-data/tools GO111MODULE=on go get github.com/cweill/gotests/...@latest
go: finding github.com/cweill/gotests/... latest
go get github.com/cweill/gotests/...@latest: no matching versions for query "latest"
go: finding github.com/cweill/gotests/... latest
go get github.com/cweill/gotests/...@latest: no matching versions for query "latest"
Press ENTER or type command to continue
```

Seems like the `gotests` repo [does not support go modules yet which breaks the `@latest` tag](https://github.com/cweill/gotests/issues/105) (based on my very limited understanding of Go's package system).

[Here](https://github.com/microsoft/vscode-go/issues/2936) is a similar issue in VSCode's corresponding extension and [here is their fix](https://github.com/microsoft/vscode-go/pull/2970).

[This PR](https://github.com/josa42/coc-go/pull/60) adding the `@latest` tag seems potentially relevant as well.

## Workaround

I was able to get around this issue by installing a more recent Go version (specifically `v1.13`). After doing so, `gotests` & `gopls` installed successfully on opening a Go file.

**Comment by josa42** [comment]
I am sorry, but I do not plan to fix this.

You can either use a more recent version of go as you mentioned. Or install `gopls` manually and set `go.goplsPath` in `cot-settings.json`.
