### ISSUE TITLE
Disable workspace folders

### ISSUE THREAD

**Issue by Akin909** [josa42/coc-go#83]
Hi 👋 thanks for this great extension.

Currently I work in quite a large monorepo and `gopls` doesn't seem to be able to handle this https://github.com/golang/go/issues/37670 for example documents that. I've found that disabling the workspace seems to improve this ie. using
```json
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "disableWorkspaceFolders": true, <----- this option
      "filetypes": ["go"]
    }
  }
```

Is there any way to pass this flag to `coc-go` I quite like the added functionality it provides like snippets, tag and test generation etc. but till `gopls` solve the issue with large monorepos I can't run `gopls` without that option.

**Comment by luisdavim** [comment]
You can pass args to `gopls` using `go.goplsArgs` in the config.

**Comment by Akin909** [comment]
@luisdavim looking at [the gopls repo](https://github.com/golang/tools/blob/master/gopls/doc/user.md) and running `gopls -h` it doesn't look like the ability to disable workspaces is one of the command line arguments the server takes. I think it has to be in the language server initialisation options somewhere, which aren't exposed

**Comment by josa42** [comment]
You can now disable workspace folders, by setting `go.disable.workspaceFolder` to `true`.

```json
{
  "go.disable": {
    "workspaceFolder": true
  }
}
