### ISSUE TITLE
Autocompletion, Linting Issue

### ISSUE THREAD

**Issue by jasontcole** [josa42/coc-go#84]
This may be a GOPATH issue, because  I am using the same vimrc on two different machines (one work machine, one personal) and coc-go isn't working on one of them.  I don't see any documentation to troubleshoot this within vim though.  I can see `no completions found` using `workspace.showOutput`.  Can someone tell me what to check?  Also, once I get this working, is there a setting where I can disable autocomplete and only use the lint function?  

vim
```
VIM - Vi IMproved 8.1
```

Services
```
* go [running] go
```

Sources 
```
* go [LS] 99 go
```

Version
```
[coc.nvim] Version: coc-go 0.8.0; gopls 0.4.1
```

go env 
```
$ go env
GOBIN=""
GOPATH="<omitted for security>/go"

<output omitted for brevity>
```

**Comment by josa42** [comment]
I cannot reproduce the issue, with the provided infos. I'd suspect it to be a problem not within this package.
