### ISSUE TITLE
Organize import action not working

### ISSUE THREAD

**Issue by sveatlo** [josa42/coc-go#85]
Hi, I'm having issues with the `editor.action.organizeImport` action. I tried both by call (as documented in README) `:call CocAction('runCommand', 'editor.action.organizeImport')` and with `:CocCommand editor.action.organizeImport`, but it always fails with an error: `[coc.nvim] Organize import action not found.`. Has something changed since the documentation has been written or am I doing something wrong?

**Comment by sijad** [comment]
it seems to be related to `gopls` itself

**Comment by sveatlo** [comment]
how? everything else seems to be working and `gopls` is in PATH

**Comment by sijad** [comment]
I followed this instruction and got same warning: https://github.com/golang/tools/blob/master/gopls/doc/vim.md#cocnvim

**Comment by sijad** [comment]
I've add `go` to `formatOnSaveFiletypes` setting and gofmt works again. I still get that warning but both organize import and gofmt works, this is my coc config:

```
{
  "coc.preferences.formatOnSaveFiletypes": ["go"],
  "languageserver": {
    "go": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "filetypes": ["go"]
    }
  }
}
```

**Comment by josa42** [comment]
I cannot reproduce this issue. If the rest of the `gopls` features work, I would suspect the issue is not in this package.
