### ISSUE TITLE
You are neither in a module nor in your GOPATH 

### ISSUE THREAD

**Issue by zdmgmail** [josa42/coc-go#88]
I use coc-go and vim-go , 

in vim-go 

```
let g:go_autodetect_gopath = 1
```

it  auto set gopath, so it always happen  "You are neither in a module nor in your GOPATH " but run the file no need do anything

I saw error #77 , add a go.mod  works

but can you add this feture  auto use default gopath and the `go_autodetect_gopath` ?

**Comment by josa42** [comment]
The implementation of [`go#path#Detect() `](https://github.com/fatih/vim-go/blob/master/autoload/go/path.vim#L76) in `vim-go` looks quite complex. I don't plan to implement or maintain that.
