### ISSUE TITLE
Error on applyEdits: Create document file: ..... timeout after 1s

### ISSUE THREAD

**Issue by GopherJ** [josa42/coc-go#93]
Hi, with coc.nvim & coc-go I'm experiencing this:

![Peek 2020-07-15 20-27](https://user-images.githubusercontent.com/33961674/87582088-2f7b4780-c6da-11ea-9d39-c6a34f367d9b.gif)

I called coc-rename, it throwed an error of timeout of 1 second

Any idea on how to fix it?

**Environment**

- Linux Mint v20
- neovim 5
- coc.nvim latest
- coc-go latest

**coc-settings.json**
![image](https://user-images.githubusercontent.com/33961674/87582284-7cf7b480-c6da-11ea-9a2c-fd383ce66094.png)

**Go version**
go version go1.14.4 linux/amd64

**Gopls version**
golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

**Comment by GopherJ** [comment]
To reproduce, vimrc is [here](https://github.com/GopherJ/cfg/blob/master/coc/.vimrc),

**Comment by josa42** [comment]
@GopherJ I cannot reproduce your issue. Could you try updating goals? (`:CocCommand go.install.gopls`)

**Comment by GopherJ** [comment]
@josa42 Thanks, seems upgrading fixed this!

**Comment by therealplato** [comment]
I'm experiencing the same error but `:CocCommand go.install.gopls` complains:
```
[coc.nvim] Error: Command failed: env GOBIN="/Users/therealplato/.config/coc/extensions/coc-go-data/bin" go get golang.org/x/tools/gopls@latest
[coc.nvim] Failed to install 'gopls'
```

When I run that manually:
```
env GOBIN="/Users/therealplato/.config/coc/extensions/coc-go-data/bin" go get golang.org/x/tools/gopls@latest
go get golang.org/x/tools/gopls@latest: module lookup disabled by GOPROXY=off
```

I saw `allowImplicitNetworkAccess` mentioned in the readme as _disabling_ GOPROXY=off, implying that the default is GOPROXY=off.

Is there a way to update gopls without setting a proxy or setting GO111MODULES=off?

Is there a way to increase the timeout?

(also @josa42 Should I open a new ticket or reopen this one?)
