### ISSUE TITLE
Command for opening suggested documentation

### ISSUE THREAD

**Issue by jaapz** [josa42/coc-go#98]
gopls suggests documentation for pkg.go.dev, however sometimes links are wrapped to newlines which makes them hard to open in the browser

![wrapped](https://user-images.githubusercontent.com/513050/91542343-00cdcf00-e91e-11ea-8eb6-547caacd7d3e.png)

I'd like to skip clicking the link at all and just run a CocCommand (which I can bind to a key) to run `xdg-open` on the link and show it in my browser

**Comment by josa42** [comment]
This is not in the scope of this package. You could open an issue for [coc.nvim](https://github.com/neoclide/coc.nvim).
